buildImage = 'ghcr.io/railwayapp/nixpacks:latest'

[phases.setup]
npm = true
nodeVersion = "20"

[phases.install]
dependsOn = ["setup"]
cacheDirectories = [
  "node_modules",
  "node_modules/.cache"]
cmds = ["npm install -g pnpm@9"]

[phases.build]
dependsOn = ["install"]
cacheDirectories = [
  "node_modules",
  "node_modules/.cache"]
cmds = ["pnpm install --frozen-lockfile", "pnpm run build"]

[start]
cmd = "node serve.js"

# Ensure build directory is included in the final image
[staticAssets]
"build" = "build"